name: First Workflow
on: workflow_dispatch #manually starts
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting 
        run: echo "Hello World!"
      - name: Print goodby
        run: echo "Done - byte!"
